const homeIcons = [{
  'id': '0015',
  'imgUrl': '/static/img/icons/home/attendance.png',
  'desc': '学生考勤',
  'router': '/attendance'
}, {
  'id': '0004',
  'imgUrl': '/static/img/icons/home/timetable.png',
  'desc': '课程表',
  'router': '/timetable'
}, {
  'id': '0010',
  'imgUrl': '/static/img/icons/home/homework.png',
  'desc': '作业',
  'router': '/homework'
}, {
  'id': '0002',
  'imgUrl': '/static/img/icons/home/notice.png',
  'desc': '通知',
  'router': '/notice/send'
}, {
  'id': '0006',
  'imgUrl': '/static/img/icons/home/health.png',
  'desc': '健康',
  'router': '/health'
}, {
  'id': '0005',
  'imgUrl': '/static/img/icons/home/recipe.png',
  'desc': '食谱',
  'router': '/recipe'
}, {
  'id': '0007',
  'imgUrl': '/static/img/icons/home/album.png',
  'desc': '班级相册',
  'router': '/album'
}, {
  'id': '0008',
  'imgUrl': '/static/img/icons/home/live.png',
  'desc': '在线视频',
  'router': '/live'
}, {
  'id': '0001',
  'imgUrl': '/static/img/icons/home/school.png',
  'desc': '学校',
  'router': '/school'
}, {
  'id': '0009',
  'imgUrl': '/static/img/icons/home/attendance-my.png',
  'desc': '个人考勤',
  'router': '/attendance/my'
}, {
  'id': '0012',
  'imgUrl': '/static/img/icons/home/contact.png',
  'desc': '通讯录',
  'router': '/contact'
}, {
  'id': '0003',
  'imgUrl': '/static/img/icons/home/message.png',
  'desc': '信箱',
  'router': '/message/receive'
}, {
  'id': '0011',
  'imgUrl': '/static/img/icons/home/recommend.png',
  'desc': '报名列表',
  'router': '/recommend/list'
}, {
  'id': '0014',
  'imgUrl': '/static/img/icons/home/advice.png',
  'desc': '意见反馈',
  'router': '/advice/create'
}
]
export { homeIcons }
